// js/services-data.js

const servicesData = [
    { id: "conversational", title: "Agentes que Actúan", description: "Acceso y ejecución de tareas en sus CRMs, bases de datos y Google Sheets. Toman decisiones o las escalan de forma inteligente.", detailed: "Creamos agentes que dialogan con naturalidad, acceden a bases de conocimiento en tiempo real y resuelven problemas complejos, mejorando la experiencia del cliente y la eficiencia interna.", useCase: "Ej: Un asistente de soporte técnico que guía a un usuario consultando manuales y el historial del CRM.", visualization: `<div class="flex items-center justify-center h-20 w-20 bg-cyan-900/20 rounded-full text-5xl animate-pulse">🤖</div>` },
    { id: "integration", title: "Análisis de Interacciones", description: "No pierda la riqueza de la comunicación. Le entregamos informes con los insights de las conversaciones para que entienda y mejore.", detailed: "Nuestra IA se conecta de forma nativa a tus fuentes de datos, sin importar el formato o la ubicación, para crear una visión unificada y coherente de tu negocio.", useCase: "Ej: Consolidación automática de ventas desde Shopify, SAP y Excel en un único dashboard.", visualization: `<div class="flex items-center justify-center h-20 w-20 bg-cyan-900/20 rounded-full animate-pulse overflow-visible"><img src="https://cdn.shopify.com/s/files/1/0663/9940/4205/files/data-trends-svgrepo-com.svg?v=1753854705" alt="Gráfico" class="h-10 w-10 object-contain p-1" /></div>` },
    { id: "reporting", title: "Reportería Inteligente", description: "Sus KPIs más importantes son analizados y reportados sin intervención humana. Céntrese en decidir, no en reportar.", detailed: "Olvida los reportes manuales. Generamos análisis visuales e interactivos que se actualizan solos, destacando KPIs, tendencias y anomalías de forma proactiva.", useCase: "Ej: Un reporte de ventas diario que se envía a gerencia con insights clave sobre el rendimiento.", visualization: `<div class="flex items-center justify-center h-20 w-20 bg-cyan-900/20 rounded-full animate-pulse overflow-visible"><img src="https://cdn.shopify.com/s/files/1/0663/9940/4205/files/statistics-svgrepo-com.svg?v=1753854082" alt="Gráfico" class="h-10 w-10 object-contain p-1" /></div>` },
    { id: "predictive", title: "Integración Total", description: "Diseñamos soluciones a medida que conectan la IA con todos tus sistemas existentes, creando un ecosistema unificado y eficiente.", detailed: "Conectamos cada parte de tu negocio para que la IA trabaje por ti. Ahorra tiempo, reduce errores y acelera tus resultados desde el día uno.", useCase: "Ej: Cuando un cliente hace una compra, el sistema actualiza el stock, envía un correo de confirmación y registra la venta en el CRM automáticamente.", visualization: `<div class="flex items-center justify-center h-20 w-20 bg-cyan-900/20 rounded-full animate-pulse overflow-visible"><img src="https://cdn.shopify.com/s/files/1/0663/9940/4205/files/integration-testing-svgrepo-com.svg?v=1753854082" alt="Gráfico" class="h-10 w-10 object-contain p-1" /></div>` },
    { id: "smart workflows", title: "Workflows Inteligentes", description: "Diagramas de flujo interactivos que muestran decisiones ramificadas.", detailed: "Creamos flujos de decisión automatizados que simulan procesos de negocio, activan acciones basadas en condiciones lógicas y se visualizan como mapas dinámicos tipo árbol.", useCase: "Ej: Un flujo de aprobación automática de contratos que escala decisiones según el monto o tipo de cliente.", visualization: `<div class="flex items-center justify-center h-20 w-20 bg-cyan-900/20 rounded-full animate-pulse overflow-visible"><img src="https://cdn.shopify.com/s/files/1/0663/9940/4205/files/workflow-svgrepo-com.svg?v=1753854081" alt="Gráfico" class="h-10 w-10 object-contain p-1" /></div>` },
    { id: "rag agent", title: "RAG Empresarial Avanzado", description: "Documentos vivos conectados a insights en tiempo real.", detailed: "Implementamos Retrieval-Augmented Generation (RAG) para conectar tus documentos empresariales a modelos de lenguaje que responden con precisión basada en evidencia. Cada respuesta está respaldada por la fuente original.", useCase: "Ej: Un asistente interno que responde preguntas sobre políticas de la empresa citando el documento exacto.", visualization: `<div class="flex items-center justify-center h-20 w-20 bg-cyan-900/20 rounded-full animate-pulse overflow-visible"><img src="https://cdn.shopify.com/s/files/1/0663/9940/4205/files/ai-platform-svgrepo-com.svg?v=1753854081" alt="Gráfico" class="h-10 w-10 object-contain p-1" /></div>` }
];